"""initial clean schema

Revision ID: 24d614bbf74d
Revises: 
Create Date: 2025-12-12 22:35:22.832401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d614bbf74d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FestivalEdition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('Start_date', sa.Date(), nullable=True),
    sa.Column('End_date', sa.Date(), nullable=True),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.Column('Location', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Genres',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('related_genre_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['related_genre_id'], ['Genres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Artists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('Artist_name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['FestivalEdition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('Question', sa.Text(), nullable=True),
    sa.Column('festival_id', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_results', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['FestivalEdition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ArtistGenres',
    sa.Column('artist_id', sa.BigInteger(), nullable=False),
    sa.Column('genre_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['Genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    op.create_table('Polloption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('Count', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Suggestion_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('festival_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], ),
    sa.ForeignKeyConstraint(['festival_id'], ['FestivalEdition.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Votes_for',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('polloption_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['polloption_id'], ['Polloption.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'polloption_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Votes_for')
    op.drop_table('Suggestion_feedback')
    op.drop_table('Polloption')
    op.drop_table('ArtistGenres')
    op.drop_table('poll')
    op.drop_table('Artists')
    op.drop_table('User')
    op.drop_table('Genres')
    op.drop_table('FestivalEdition')
    # ### end Alembic commands ###
